import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "bootstrap-icons/font/bootstrap-icons.css";
import {CartProvider} from "@/app/[number]/contexts/CartContext";
import {FilterProvider} from "@/app/[number]/contexts/FilterContext";
import {Suspense} from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <CartProvider>
          <Suspense>
              <FilterProvider>
                  {children}
              </FilterProvider>
          </Suspense>
      </CartProvider>
  );
}
