import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "bootstrap-icons/font/bootstrap-icons.css";
import './global.css'
import './theme.css'
import { Roboto } from 'next/font/google';
import {CartProvider} from "@/app/[number]/contexts/CartContext";
import {FilterProvider} from "@/app/[number]/contexts/FilterContext";
import {QueryProvider} from "@/app/providers/QueryProvider";
import {Suspense} from "react";
import {TransitionProvider} from "@/app/contexts/transition-context";
import TransitionWrapper from "@/app/components/transition-wrapper";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],             // estilos desejados
  display: 'swap',
  variable: '--font-roboto',           // opcional, se quiser usar CSS var
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
    <QueryProvider>
      <TransitionProvider>
          {children}
      </TransitionProvider>
    </QueryProvider>
    </body>
    </html>
  );
}
